CSVIO: csvio::util Namespace Reference
csvio::util Namespace Reference
Classes
class CSVInputParser
Class of functions to parse a csv row into a non map container.
class CSVLineReader
Stateful CSV line reader which reads csv lines with escaped fields according to RFC 4180.
class CSVLineWriter
Writes a csv line to a stream, provides a written lines counter.
class CSVOutputFormatter
a class describing how csv output should be formatted
class has_push_back
SFINAE Helper to determine if T has a push_back method.
struct has_push_back< C, Ret(Args...)>
Enumerations
enum CSVParserScope { LINE, QUOTE }
Functions
std::string escape (std::string_view data, char delim=',', bool force_escape=false)
function to escape characters in csv fields according to RFC 4180
std::string unescape (std::string_view data)
unescape a csv escaped string according to RFC 4180
Enumeration Type Documentation
CSVParserScope
enum csvio::util::CSVParserScope
Enumerator
LINE
QUOTE
Definition at line 161 of file csv_io.hpp.
Function Documentation
escape()
std::string csvio::util::escape (std::string_view data, char delim = ',', bool force_escape = false) inline
function to escape characters in csv fields according to RFC 4180
Source: https://tools.ietf.org/html/rfc4180
If discoverd that the string doesn't have any characters which need to be escaped, the string will not be enclosed in quotes
Also handles alternative delimiters and allows forced escapes which will append leading and trailing double quotes
Generally O(n) avg time and space complexity
Parameters
data string to escape
delim used to check if a delimiter is in the field. if so, it should be escaped
force_escape wrap the string in quotes even if not needed
Returns
escaped csv field if necessary, otherwise the string
Definition at line 101 of file csv_io.hpp.
Referenced by csvio::util::CSVOutputFormatter< RowContainer >::delim_join_escaped_fmt().
unescape()
std::string csvio::util::unescape (std::string_view data) inline
unescape a csv escaped string according to RFC 4180
Generally linear avg time and space complexity
Parameters
data string_view csv data to unescape
Returns
unquoted csv field
Definition at line 136 of file csv_io.hpp.
Referenced by csvio::util::CSVInputParser< RowContainer >::delim_split_unescaped_impl(), and csvio::util::CSVInputParser< RowContainer >::delim_split_unescaped_threaded_impl().