CSVIO: csvio::util::MapDelimSplitUnescapedThreaded< RowMapContainer > Class Template Reference
csvio::util::MapDelimSplitUnescapedThreaded< RowMapContainer > Class Template Reference
Split a CSV to a map container assuming the values are escaped, and unescape output.
#include <csv_io.hpp>
Public Member Functions
void delim_split_escaped_impl (string_view input, const char delim, vector< string > &header_names)
implementation of delim_split_escaped for map types
void delim_split_unescaped_threaded_impl (string_view input, const char delim, vector< string > &header_names)
split and unescape the fields in the csv with a thread for each value
RowMapContainer< string, string > & operator() (string_view input, const char delim, vector< string > &header_names)
split a csv row on a delimiter unescaping the output strings
Public Attributes
RowMapContainer< string, string > m_data
Detailed Description
template<template< class... > class RowMapContainer>
class csvio::util::MapDelimSplitUnescapedThreaded< RowMapContainer >
Split a CSV to a map container assuming the values are escaped, and unescape output.
Definition at line 545 of file csv_io.hpp.
Member Function Documentation
delim_split_escaped_impl()
template<template< class... > class RowMapContainer> void csvio::util::MapDelimSplitUnescapedThreaded< RowMapContainer >::delim_split_escaped_impl (string_view input, const char delim, vector< string > & header_names) inline
implementation of delim_split_escaped for map types
Linear time complexity with respect to the size of input
Parameters
input string_view to split by delimiter
delim delimiter to split on
header_names input canonical header names
Definition at line 567 of file csv_io.hpp.
References csvio::util::LINE, csvio::util::MapDelimSplitUnescapedThreaded< RowMapContainer >::m_data, and csvio::util::QUOTE.
Referenced by csvio::util::MapDelimSplitUnescapedThreaded< RowMapContainer >::delim_split_unescaped_threaded_impl().
delim_split_unescaped_threaded_impl()
template<template< class... > class RowMapContainer> void csvio::util::MapDelimSplitUnescapedThreaded< RowMapContainer >::delim_split_unescaped_threaded_impl (string_view input, const char delim, vector< string > & header_names) inline
split and unescape the fields in the csv with a thread for each value
Parameters
input string_view to split by delimiter
delim delimiter to split on
header_names input canonical header names
Definition at line 610 of file csv_io.hpp.
References csvio::util::MapDelimSplitUnescapedThreaded< RowMapContainer >::delim_split_escaped_impl(), csvio::util::MapDelimSplitUnescapedThreaded< RowMapContainer >::m_data, and csvio::util::unescape().
Referenced by csvio::util::MapDelimSplitUnescapedThreaded< RowMapContainer >::operator()().
operator()()
template<template< class... > class RowMapContainer> RowMapContainer<string, string>& csvio::util::MapDelimSplitUnescapedThreaded< RowMapContainer >::operator() (string_view input, const char delim, vector< string > & header_names) inline
split a csv row on a delimiter unescaping the output strings
Parameters
input string_view to split by a delimiter
delim delimiter to split input on
header_names input canonical header names
Returns
RowMapContainer of split csv fields
Definition at line 552 of file csv_io.hpp.
References csvio::util::MapDelimSplitUnescapedThreaded< RowMapContainer >::delim_split_unescaped_threaded_impl(), and csvio::util::MapDelimSplitUnescapedThreaded< RowMapContainer >::m_data.
Member Data Documentation
m_data
template<template< class... > class RowMapContainer> RowMapContainer<string, string> csvio::util::MapDelimSplitUnescapedThreaded< RowMapContainer >::m_data
Definition at line 624 of file csv_io.hpp.
Referenced by csvio::util::MapDelimSplitUnescapedThreaded< RowMapContainer >::delim_split_escaped_impl(), csvio::util::MapDelimSplitUnescapedThreaded< RowMapContainer >::delim_split_unescaped_threaded_impl(), and csvio::util::MapDelimSplitUnescapedThreaded< RowMapContainer >::operator()().
The documentation for this class was generated from the following file:
include/csv_io.hpp