CSVIO: csvio::util::CSVInputParser< RowContainer > Class Template Reference
csvio::util::CSVInputParser< RowContainer > Class Template Reference
Class of functions to parse a csv row into a non map container.
#include <csv_io.hpp>
Static Public Member Functions
static RowContainer< std::string > delim_split_escaped (std::string_view input, const char delim)
Split string_view csv row based on a delimiter with escaped fields.
static void delim_split_escaped_impl (std::string_view input, const char delim)
implementation of delim_split_escaped
static RowContainer< std::string > delim_split_naive (const std::string &input, const char delim)
Split string_view csv row based on a delimiter.
static RowContainer< std::string > delim_split_unescaped (std::string_view input, const char delim)
split a csv row on a delimiter escaping the output strings
static void delim_split_unescaped_impl (std::string_view input, const char delim)
implementation of delim_split_unescaped
static RowContainer< std::string > delim_split_unescaped_threaded (std::string_view input, const char delim)
split a csv row on a delimiter escaping the output strings threaded
static void delim_split_unescaped_threaded_impl (std::string_view input, const char delim)
implementation of delim_split_unescaped_threaded
Static Public Attributes
static RowContainer< std::string > m_data
Detailed Description
template<template< class... > class RowContainer>
class csvio::util::CSVInputParser< RowContainer >
Class of functions to parse a csv row into a non map container.
These functions assume the container has a push_back method
Definition at line 181 of file csv_io.hpp.
Member Function Documentation
delim_split_escaped()
template<template< class... > class RowContainer> static RowContainer<std::string> csvio::util::CSVInputParser< RowContainer >::delim_split_escaped (std::string_view input, const char delim) inline static
Split string_view csv row based on a delimiter with escaped fields.
Parameters
input string_view to split by delimiter
delim delimiter to split on
Returns
RowContainer of split csv fields, if input string empty, return RowContainer with one empty string
Definition at line 262 of file csv_io.hpp.
References csvio::util::CSVInputParser< RowContainer >::delim_split_escaped_impl(), and csvio::util::CSVInputParser< RowContainer >::m_data.
delim_split_escaped_impl()
template<template< class... > class RowContainer> static void csvio::util::CSVInputParser< RowContainer >::delim_split_escaped_impl (std::string_view input, const char delim) inline static
implementation of delim_split_escaped
Linear time complexity with respect to the size of input
Parameters
input string_view to split by delimiter
delim delimiter to split on
Returns
RowContainer of split csv fields, if input string empty, return RowContainer with one empty string
Definition at line 218 of file csv_io.hpp.
References csvio::util::LINE, csvio::util::CSVInputParser< RowContainer >::m_data, and csvio::util::QUOTE.
Referenced by csvio::util::CSVInputParser< RowContainer >::delim_split_escaped(), csvio::util::CSVInputParser< RowContainer >::delim_split_unescaped_impl(), and csvio::util::CSVInputParser< RowContainer >::delim_split_unescaped_threaded_impl().
delim_split_naive()
template<template< class... > class RowContainer> static RowContainer<std::string> csvio::util::CSVInputParser< RowContainer >::delim_split_naive (const std::string & input, const char delim) inline static
Split string_view csv row based on a delimiter.
Linear time complexity with respect to the size of input
Parameters
input string_view to split by delimiter
delim delimiter to split on
Returns
RowContainer of split csv fields
Definition at line 191 of file csv_io.hpp.
References csvio::util::CSVInputParser< RowContainer >::m_data.
delim_split_unescaped()
template<template< class... > class RowContainer> static RowContainer<std::string> csvio::util::CSVInputParser< RowContainer >::delim_split_unescaped (std::string_view input, const char delim) inline static
split a csv row on a delimiter escaping the output strings
Parameters
input string_view to split by delimiter
delim delimiter to split on
Returns
RowContainer of split csv fields, if input string empty, return RowContainer with one empty string
Definition at line 288 of file csv_io.hpp.
References csvio::util::CSVInputParser< RowContainer >::delim_split_unescaped_impl(), and csvio::util::CSVInputParser< RowContainer >::m_data.
delim_split_unescaped_impl()
template<template< class... > class RowContainer> static void csvio::util::CSVInputParser< RowContainer >::delim_split_unescaped_impl (std::string_view input, const char delim) inline static
implementation of delim_split_unescaped
O(2N) where n is the size of the input
Parameters
input string_view to split by delimiter
delim delimiter to split on
Returns
RowContainer of split csv fields, if input string empty, return RowContainer with one empty string
Definition at line 277 of file csv_io.hpp.
References csvio::util::CSVInputParser< RowContainer >::delim_split_escaped_impl(), csvio::util::CSVInputParser< RowContainer >::m_data, and csvio::util::unescape().
Referenced by csvio::util::CSVInputParser< RowContainer >::delim_split_unescaped(), and csvio::util::CSVInputParser< RowContainer >::delim_split_unescaped_threaded().
delim_split_unescaped_threaded()
template<template< class... > class RowContainer> static RowContainer<std::string> csvio::util::CSVInputParser< RowContainer >::delim_split_unescaped_threaded (std::string_view input, const char delim) inline static
split a csv row on a delimiter escaping the output strings threaded
Parameters
input string_view to split by delimiter
delim delimiter to split on
Returns
RowContainer of split csv fields, if input string empty, return RowContainer with one empty string
Definition at line 322 of file csv_io.hpp.
References csvio::util::CSVInputParser< RowContainer >::delim_split_unescaped_impl(), and csvio::util::CSVInputParser< RowContainer >::m_data.
delim_split_unescaped_threaded_impl()
template<template< class... > class RowContainer> static void csvio::util::CSVInputParser< RowContainer >::delim_split_unescaped_threaded_impl (std::string_view input, const char delim) inline static
implementation of delim_split_unescaped_threaded
Parameters
input string_view to split by delimiter
delim delimiter to split on
Returns
RowContainer of split csv fields, if input string empty, return RowContainer with one empty string
Definition at line 301 of file csv_io.hpp.
References csvio::util::CSVInputParser< RowContainer >::delim_split_escaped_impl(), csvio::util::CSVInputParser< RowContainer >::m_data, and csvio::util::unescape().
Member Data Documentation
m_data
template<template< class... > class RowContainer> RowContainer< std::string > csvio::util::CSVInputParser< RowContainer >::m_data static
Definition at line 182 of file csv_io.hpp.
Referenced by csvio::util::CSVInputParser< RowContainer >::delim_split_escaped(), csvio::util::CSVInputParser< RowContainer >::delim_split_escaped_impl(), csvio::util::CSVInputParser< RowContainer >::delim_split_naive(), csvio::util::CSVInputParser< RowContainer >::delim_split_unescaped(), csvio::util::CSVInputParser< RowContainer >::delim_split_unescaped_impl(), csvio::util::CSVInputParser< RowContainer >::delim_split_unescaped_threaded(), and csvio::util::CSVInputParser< RowContainer >::delim_split_unescaped_threaded_impl().
The documentation for this class was generated from the following file:
include/csv_io.hpp