CSVIO: csvio::util::DelimSplitUnescaped< RowContainer > Class Template Reference
csvio::util::DelimSplitUnescaped< RowContainer > Class Template Reference
Split a CSV assuming it is escaped and unescape the output.
#include <csv_io.hpp>
Public Member Functions
void delim_split_escaped_impl (string_view input, const char delim)
implementation of delim_split_escaped
void delim_split_unescaped_impl (string_view input, const char delim)
implementation of delim_split_unescaped
RowContainer< string > & operator() (string_view input, const char delim)
split a csv row on a delimiter unescaping the output strings threaded
Public Attributes
RowContainer< string > m_data
Detailed Description
template<template< class... > class RowContainer>
class csvio::util::DelimSplitUnescaped< RowContainer >
Split a CSV assuming it is escaped and unescape the output.
Definition at line 385 of file csv_io.hpp.
Member Function Documentation
delim_split_escaped_impl()
template<template< class... > class RowContainer> void csvio::util::DelimSplitUnescaped< RowContainer >::delim_split_escaped_impl (string_view input, const char delim) inline
implementation of delim_split_escaped
Linear time complexity with respect to the size of input
Parameters
input string_view to split by delimiter
delim delimiter to split on
Returns
RowContainer of split csv fields, if input string empty, return RowContainer with one empty string
Definition at line 407 of file csv_io.hpp.
References csvio::util::LINE, csvio::util::DelimSplitUnescaped< RowContainer >::m_data, and csvio::util::QUOTE.
Referenced by csvio::util::DelimSplitUnescaped< RowContainer >::delim_split_unescaped_impl().
delim_split_unescaped_impl()
template<template< class... > class RowContainer> void csvio::util::DelimSplitUnescaped< RowContainer >::delim_split_unescaped_impl (string_view input, const char delim) inline
implementation of delim_split_unescaped
O(2N) where n is the size of the input
Parameters
input string_view to split by a delimiter
delim delimiter to split on
Returns
RowContainer of split csv fields, if input string empty, return RowContainer with one empty string
Definition at line 453 of file csv_io.hpp.
References csvio::util::DelimSplitUnescaped< RowContainer >::delim_split_escaped_impl(), csvio::util::DelimSplitUnescaped< RowContainer >::m_data, and csvio::util::unescape().
Referenced by csvio::util::DelimSplitUnescaped< RowContainer >::operator()().
operator()()
template<template< class... > class RowContainer> RowContainer<string>& csvio::util::DelimSplitUnescaped< RowContainer >::operator() (string_view input, const char delim) inline
split a csv row on a delimiter unescaping the output strings threaded
Parameters
input string_view to split by delimiter
delim delimiter to split on
Returns
RowContainer of split csv fields, if input string empty, return RowContainer with one empty string
Definition at line 392 of file csv_io.hpp.
References csvio::util::DelimSplitUnescaped< RowContainer >::delim_split_unescaped_impl(), and csvio::util::DelimSplitUnescaped< RowContainer >::m_data.
Member Data Documentation
m_data
template<template< class... > class RowContainer> RowContainer<string> csvio::util::DelimSplitUnescaped< RowContainer >::m_data
Definition at line 458 of file csv_io.hpp.
Referenced by csvio::util::DelimSplitUnescaped< RowContainer >::delim_split_escaped_impl(), csvio::util::DelimSplitUnescaped< RowContainer >::delim_split_unescaped_impl(), and csvio::util::DelimSplitUnescaped< RowContainer >::operator()().
The documentation for this class was generated from the following file:
include/csv_io.hpp